default_context:
  project_name: 'Epic ERP'
  project_slug: 'epic-erp'
  domain_main: 'epic-erp.akhilnarang.dev'
  domain_staging: 'stag.epic-erp.akhilnarang.dev'
  docker_swarm_stack_name_main: 'epic-erp-akhilnarang-dev'
  docker_swarm_stack_name_staging: 'stag-epic-erp-akhilnarang-dev'
  secret_key: '24f9625be8604662610b5c42d0b6382e1dcc31a5d2e68c44e6f753f4c732409a'
  first_superuser: 'admin@epic-erp.akhilnarang.dev'
  first_superuser_password: '919399cb35d7ccf9e2bb3c4ce30e86f3d1258ae841f43281dab20560880ef676'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.epic-erp.akhilnarang.dev", "https://stag.epic-erp.akhilnarang.dev", "https://epic-erp.akhilnarang.dev", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'epic-erp@akhilnarang.dev'
  postgres_password: '2d839bf8e9b767d0151637c92d232795812bce4cc6bc2ee59ad9099f37867e9c'
  pgadmin_default_user: 'admin@epic-erp.akhilnarang.dev'
  pgadmin_default_user_password: '919399cb35d7ccf9e2bb3c4ce30e86f3d1258ae841f43281dab20560880ef676'
  traefik_constraint_tag: 'epic-erp.akhilnarang.dev'
  traefik_constraint_tag_staging: 'stag.epic-erp.akhilnarang.dev'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:919399cb35d7ccf9e2bb3c4ce30e86f3d1258ae841f43281dab20560880ef676'
  sentry_dsn: ''
  docker_image_prefix: 'epic-erp_'
  docker_image_backend: 'epic-erp_backend'
  docker_image_celeryworker: 'epic-erp_celeryworker'
  docker_image_frontend: 'epic-erp_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
