version: "3.3"
services:

  db:
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432

  backend:
    image: ghcr.io/rev-amp/backend
    command: bash tests-start.sh
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app

volumes:
  app:
