version: "3.3"
services:

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    volumes:
      - ../database:/var/lib/postgresql/data

  backend:
    image: ghcr.io/rev-amp/backend
    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --workers=4
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./app:/app

volumes:
  app:
