[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.11.3"
fastapi = "^0.54.1"
python-multipart = "^0.0.5"
email-validator = "^1.0.5"
requests = "^2.23.0"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^6.1.0"
pydantic = {extras = ["dotenv"], version = "^1.7.3"}
emails = "^0.5.15"
raven = "^6.10.0"
gunicorn = "^20.0.4"
jinja2 = "^2.11.2"
psycopg2-binary = "^2.8.6"
alembic = "^1.4.2"
sqlalchemy = "^1.3.16"
pytest = "^6.1.2"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
python-decouple = "^3.3"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
black = "^20.8b1"
isort = "^5.6.4"
autoflake = "^1.4"
flake8 = "^3.8.4"
pytest = "^6.1.2"
sqlalchemy-stubs = "^0.3"
pytest-cov = "^2.10.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88

[tool.black]
line-length = 120

[tool.pytest.ini_options]
filterwarnings = ["ignore", ":::imported_lib"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

