[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.14.0"
fastapi = "^0.65.2"
python-multipart = "^0.0.5"
email-validator = "^1.1.3"
requests = "^2.25.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
tenacity = "^7.0.0"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
emails = "^0.6"
raven = "^6.10.0"
gunicorn = "^20.1.0"
jinja2 = "^2.11.2"
psycopg2-binary = "^2.9.1"
alembic = "^1.6.5"
sqlalchemy = "^1.3.16"
pytest = "^6.2.4"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-decouple = "^3.4"
sentry-sdk = "^1.1.0"
SQLAlchemy = "^1.4.20"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
black = "^21.6b0"
isort = "^5.9.1"
autoflake = "^1.4"
flake8 = "^3.9.2"
pytest = "^6.2.4"
sqlalchemy-stubs = "^0.4"
pytest-cov = "^2.12.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88

[tool.black]
line-length = 120

[tool.pytest.ini_options]
filterwarnings = ["ignore", ":::imported_lib"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

