on: pull_request
name: Run linting checks and tests
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Check Linting.
        run: |
          cd ./backend/app
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
          pip3 install $($HOME/.poetry/bin/poetry export --dev --without-hashes | egrep "black|mypy|isort|flake8|pydantic|sqlalchemy-stubs" | cut -d';' -f1)
          PATH=$HOME/.local/bin:$PATH ./scripts/lint.sh
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Run tests.
        run: |
          cat > .env << EOF
          DOMAIN=localhost
          STACK_NAME=epic-erp-ci-env
          TRAEFIK_PUBLIC_NETWORK=traefik-public
          TRAEFIK_TAG=epic-erp.ci.env
          TRAEFIK_PUBLIC_TAG=traefik-public
          DOCKER_IMAGE_BACKEND=epic-erp_backend
          DOCKER_IMAGE_CELERYWORKER=epic-erp_celeryworker
          BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080"]
          PROJECT_NAME=Epic ERP
          SECRET_KEY=$(openssl rand -hex 32)
          FIRST_SUPERUSER=admin@epic-erp.ci.env
          FIRST_SUPERUSER_PASSWORD=$(openssl rand -hex 32)
          SMTP_TLS=True
          SMTP_PORT=587
          SMTP_HOST=
          SMTP_USER=
          SMTP_PASSWORD=
          EMAILS_FROM_EMAIL=epic-erp@ci.env
          USERS_OPEN_REGISTRATION=False
          SENTRY_DSN=
          # Flower
          FLOWER_BASIC_AUTH=admin:$(openssl rand -hex 32)
          # Postgres
          POSTGRES_SERVER=db
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=$(openssl rand -hex 32)
          POSTGRES_DB=app
          # PgAdmin
          PGADMIN_LISTEN_PORT=5050
          PGADMIN_DEFAULT_EMAIL=admin@epic-erp.ci.env
          PGADMIN_DEFAULT_PASSWORD=$(openssl rand -hex 32)
          EOF

          ./scripts/test.sh
